import Link from "next/link";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import {
  destinationCosts,
  ebrtFaqs,
  EBRT_NAME,
  indiaCityCosts,
  techniques,
} from "@/data/ebrt-guide";
import { costPath, doctorsPath, hospitalsPath } from "@/lib/catalog-links";

const ebrtDoctors = doctorsPath({ destination: "India", procedure: EBRT_NAME });
const ebrtHospitals = hospitalsPath({ destination: "India", procedure: EBRT_NAME });

function P({ children }: { children: React.ReactNode }) {
  return <p className="mt-4 text-base leading-relaxed text-muted-foreground">{children}</p>;
}

function H2({ id, children }: { id: string; children: React.ReactNode }) {
  return (
    <h2 id={id} className="mt-14 scroll-mt-28 font-heading text-3xl">
      {children}
    </h2>
  );
}

function H3({ children }: { children: React.ReactNode }) {
  return <h3 className="mt-8 font-heading text-2xl">{children}</h3>;
}

export function EbrtGuide() {
  return (
    <article className="max-w-3xl [&_a]:underline-offset-4 [&_a]:hover:underline">
      <nav className="rounded-2xl border border-border bg-card p-6 text-sm">
        <p className="text-xs tracking-[0.18em] uppercase text-gold">On this page</p>
        <ul className="mt-3 grid gap-2 sm:grid-cols-2">
          {[
            ["what", "What is EBRT"],
            ["how", "How it works"],
            ["when", "When it is used"],
            ["types", "Techniques"],
            ["planning", "Planning"],
            ["sessions", "Sessions"],
            ["cost", "Cost in India"],
            ["package", "What is included"],
            ["recovery", "Recovery"],
            ["faq", "FAQs"],
          ].map(([id, label]) => (
            <li key={id}>
              <a href={`#${id}`} className="underline-offset-4 hover:underline">
                {label}
              </a>
            </li>
          ))}
        </ul>
      </nav>

      <P>
        External Beam Radiation Therapy (EBRT) is one of the most widely used forms of
        radiation treatment for cancer. It uses a machine outside the body to deliver
        carefully planned, high-energy radiation to a tumour or area at risk of cancer
        cells.
      </P>
      <P>
        EBRT can be used to cure cancer, control tumour growth, reduce the risk of
        recurrence, or relieve symptoms such as pain, bleeding, or pressure caused by an
        advanced tumour.
      </P>
      <P>
        Modern EBRT is not limited to conventional radiation. Depending on the cancer and
        treatment plan, it may be delivered using{" "}
        <Link href={costPath("3D Conformal Radiotherapy (3D-CRT)")}>3D-CRT</Link>,{" "}
        <Link href={costPath("Intensity-Modulated Radiotherapy (IMRT)")}>IMRT</Link>,{" "}
        <Link href={costPath("Image-Guided Radiotherapy (IGRT)")}>IGRT</Link>, VMAT,{" "}
        <Link href={costPath("Stereotactic Radiosurgery (SRS)")}>SRS</Link> or{" "}
        <Link href={costPath("Stereotactic Body Radiotherapy (SBRT)")}>SBRT</Link>.
      </P>
      <P>
        For international patients, India is one of the more cost-competitive destinations
        for{" "}
        <Link href={hospitalsPath({ destination: "India", specialty: "Radiation Oncology" })}>radiation oncology</Link>.
        Published 2026 estimates show conventional and advanced radiation courses in India
        generally costing considerably less than comparable treatment in many Western
        markets, although the actual price depends on the technique, number of fractions,{" "}
        <Link href={ebrtHospitals}>hospital</Link> and cancer type. Browse{" "}
        <Link href={ebrtDoctors}>named radiation oncologists</Link> before you book a
        flight.
      </P>

      <H2 id="what">What is External Beam Radiation Therapy?</H2>
      <P>
        External Beam Radiation Therapy is a non-invasive cancer treatment in which
        radiation is generated by a machine, most commonly a linear accelerator (LINAC),
        and directed toward a specific area of the body.
      </P>
      <P>
        The radiation damages the DNA of cancer cells. Because cancer cells are generally
        less capable of repairing radiation-induced DNA damage than normal cells, repeated
        doses can gradually eliminate or control the tumour. The radiation does not remain
        inside the body after treatment.
      </P>
      <P>A typical EBRT session involves:</P>
      <ul className="mt-4 list-disc space-y-2 pl-5 text-muted-foreground">
        <li>The patient lies on a treatment table.</li>
        <li>The body is positioned using marks and immobilisation devices created during planning.</li>
        <li>The treatment machine rotates around or moves into position around the patient.</li>
        <li>Radiation is delivered from one or more directions.</li>
        <li>The patient remains awake and does not normally feel the radiation.</li>
      </ul>
      <P>
        The session usually takes only a few minutes, although the entire appointment can
        take longer because of positioning and verification. Most conventional courses
        involve multiple fractions, often delivered five days a week over several weeks.
        Shorter schedules are increasingly used for selected cancers — see{" "}
        <Link href={costPath("Stereotactic Body Radiotherapy (SBRT)")}>SBRT</Link> and{" "}
        <Link href={costPath("Stereotactic Radiosurgery (SRS)")}>SRS</Link>.
      </P>

      <H2 id="how">How does EBRT work?</H2>
      <P>Radiation damages the DNA inside cells. Cancer cells that receive sufficient damage may stop dividing, lose their ability to reproduce, die immediately or over time, or become easier for the immune system to clear.</P>
      <P>
        Treatment is normally divided into multiple fractions rather than delivering the
        entire dose at once. This allows healthy tissues surrounding the tumour to repair
        some of the radiation damage between treatments.
      </P>
      <P>
        The{" "}
        <Link href={doctorsPath({ destination: "India", specialty: "Radiation Oncology" })}>radiation oncologist</Link>{" "}
        determines the total dose, number of fractions, size and location of the treatment
        field, radiation technique, dose distribution, and organs that need to be
        protected. The prescription depends on cancer type, stage, tumour location and
        treatment objective. Read{" "}
        <Link href="/blogs/records-before-you-book-ebrt">which records to send before travel</Link>
        .
      </P>

      <H2 id="when">When is EBRT used?</H2>
      <P>EBRT can be used for many cancers. Common applications include:</P>
      <dl className="mt-6 space-y-5">
        <div>
          <dt className="font-medium">Breast cancer</dt>
          <dd className="mt-1 text-muted-foreground">
            Radiation may be recommended after breast-conserving surgery and in selected
            patients after mastectomy — including at women&apos;s-cancer floors such as{" "}
            <Link href="/hospitals/apollo-athenaa-women-s-cancer-centre">Apollo Athenaa</Link>.
          </dd>
        </div>
        <div>
          <dt className="font-medium">Prostate cancer</dt>
          <dd className="mt-1 text-muted-foreground">
            EBRT can be used as a definitive treatment for localized or locally advanced
            prostate cancer and may also be used in other treatment settings.
          </dd>
        </div>
        <div>
          <dt className="font-medium">Lung cancer</dt>
          <dd className="mt-1 text-muted-foreground">
            Radiation can be used alone or with chemotherapy, immunotherapy or surgery.
            Selected tumours are treated with{" "}
            <Link href={costPath("Stereotactic Body Radiotherapy (SBRT)")}>SBRT</Link>{" "}
            rather than a long conventional course.
          </dd>
        </div>
        <div>
          <dt className="font-medium">Head and neck cancer</dt>
          <dd className="mt-1 text-muted-foreground">
            <Link href={costPath("Intensity-Modulated Radiotherapy (IMRT)")}>IMRT</Link>{" "}
            is frequently used to spare salivary glands, spinal cord and other healthy
            tissues. See{" "}
            <Link href="/blogs/imrt-vs-3d-crt">IMRT versus 3D-CRT</Link>.
          </dd>
        </div>
        <div>
          <dt className="font-medium">Brain tumours</dt>
          <dd className="mt-1 text-muted-foreground">
            Radiation can be used after surgery, as primary treatment, or for recurrent
            or metastatic disease. Focal work may be{" "}
            <Link href={costPath("Stereotactic Radiosurgery (SRS)")}>SRS</Link>,{" "}
            <Link href={costPath("Gamma Knife")}>Gamma Knife</Link> or{" "}
            <Link href={costPath("CyberKnife")}>CyberKnife</Link>.
          </dd>
        </div>
        <div>
          <dt className="font-medium">Cervical cancer</dt>
          <dd className="mt-1 text-muted-foreground">
            External radiation is commonly combined with{" "}
            <Link href={costPath("Brachytherapy")}>brachytherapy</Link> — often{" "}
            <Link href={costPath("Intracavitary Brachytherapy")}>intracavitary</Link> — in
            definitive treatment. Logistics are covered in{" "}
            <Link href="/blogs/brachytherapy-travel-logistics">this planning note</Link>.
          </dd>
        </div>
        <div>
          <dt className="font-medium">Rectal and colorectal cancer</dt>
          <dd className="mt-1 text-muted-foreground">
            Radiation may form part of a multidisciplinary plan, particularly for rectal
            cancer.
          </dd>
        </div>
        <div>
          <dt className="font-medium">Liver and pancreatic cancer</dt>
          <dd className="mt-1 text-muted-foreground">
            Selected patients may receive{" "}
            <Link href={costPath("Stereotactic Body Radiotherapy (SBRT)")}>SBRT</Link>{" "}
            rather than conventional fractionation.
          </dd>
        </div>
        <div>
          <dt className="font-medium">Bone metastases</dt>
          <dd className="mt-1 text-muted-foreground">
            Short-course or even single-fraction radiation can be used to relieve pain
            from cancer that has spread to bone.
          </dd>
        </div>
      </dl>

      <H2 id="types">Types of External Beam Radiation Therapy</H2>
      <P>
        EBRT is an umbrella term. Several technologies can deliver external radiation.
        Not every patient needs the most expensive machine. The named consultant selects
        the technique from the tumour and the clinical objective.
      </P>
      <div className="mt-6 overflow-x-auto rounded-2xl border border-border">
        <table className="w-full min-w-[32rem] text-left text-sm">
          <thead className="bg-secondary/60 text-xs tracking-[0.16em] uppercase text-muted-foreground">
            <tr>
              <th className="px-4 py-3 font-medium">Technique</th>
              <th className="px-4 py-3 font-medium">What it does</th>
            </tr>
          </thead>
          <tbody>
            {techniques.map((row) => (
              <tr key={row.name} className="border-t border-border bg-card">
                <td className="px-4 py-3 font-medium">
                  {row.procedure ? (
                    <Link href={costPath(row.procedure)} className="underline-offset-4 hover:underline">
                      {row.name}
                    </Link>
                  ) : (
                    row.name
                  )}
                </td>
                <td className="px-4 py-3 text-muted-foreground">{row.what}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <H3>EBRT vs IMRT vs IGRT</H3>
      <P>
        These terms confuse patients. <strong className="text-foreground">EBRT</strong>{" "}
        is the broad category of radiation delivered from outside the body.{" "}
        <Link href={costPath("Intensity-Modulated Radiotherapy (IMRT)")}>IMRT</Link> is
        an advanced form in which the intensity of different portions of the beam can be
        varied, which helps wrap dose around irregular tumours.{" "}
        <Link href={costPath("Image-Guided Radiotherapy (IGRT)")}>IGRT</Link> uses
        imaging to verify position and tumour location before or during treatment. IGRT
        and IMRT are often used together, so a course may be described as IMRT with IGRT
        rather than as two separate treatments.
      </P>

      <H2 id="planning">How is EBRT planned?</H2>
      <P>Radiation is not a matter of pointing a machine at a tumour.</P>
      <H3>1. Consultation</H3>
      <P>
        The radiation oncologist reviews diagnosis, pathology, CT/MRI/PET, previous
        surgery, chemotherapy, prior radiation, stage and overall health, then decides
        whether radiation is appropriate.{" "}
        <Link href={`/consult?treatment=${encodeURIComponent("external-beam-radiotherapy-ebrt")}`}>
          Request a dossier
        </Link>{" "}
        to meet a named consultant on camera.
      </P>
      <H3>2. CT simulation</H3>
      <P>
        A planning CT is taken in the treatment position. Immobilisation may include a
        head-and-neck mask, vacuum cushion, body mould, or limb rest so the same set-up
        can be repeated every fraction.
      </P>
      <H3>3. Treatment planning</H3>
      <P>
        The oncologist outlines the target, areas at risk, and organs to protect.
        Physicists and dosimetrists calculate dose, beam angles, intensity, fractions and
        organ-at-risk constraints. The plan undergoes quality assurance before the first
        fraction.
      </P>

      <H2 id="sessions">How many EBRT sessions are required?</H2>
      <P>There is no single number for every patient. Depending on disease and intent, radiation may be delivered in:</P>
      <ul className="mt-4 list-disc space-y-2 pl-5 text-muted-foreground">
        <li>1 session</li>
        <li>3–5 sessions</li>
        <li>10 sessions</li>
        <li>15–20 sessions</li>
        <li>25–30 sessions</li>
        <li>30–35+ sessions</li>
      </ul>
      <P>
        Traditional curative courses commonly run five days a week for several weeks.
        Hypofractionated treatments deliver larger doses per session over a shorter
        period. Indian cost sources similarly report typical courses of roughly 15–35
        sessions depending on technique and diagnosis.
      </P>

      <H2 id="pain">Is EBRT painful?</H2>
      <P>
        Delivery itself is generally painless. Patients do not normally feel the
        radiation. Side effects can develop during or after a course and depend on which
        part of the body is treated.
      </P>
      <ul className="mt-4 list-disc space-y-2 pl-5 text-muted-foreground">
        <li>
          <span className="text-foreground">Head &amp; neck:</span> mouth soreness,
          difficulty swallowing, dry mouth, taste changes, skin irritation
        </li>
        <li>
          <span className="text-foreground">Chest:</span> fatigue, skin irritation, cough
          or swallowing discomfort in some patients
        </li>
        <li>
          <span className="text-foreground">Abdomen/pelvis:</span> diarrhoea, nausea,
          urinary symptoms, bowel changes, fatigue
        </li>
        <li>
          <span className="text-foreground">Brain:</span> fatigue, headache, hair loss in
          the treated area, swelling in selected cases
        </li>
      </ul>
      <P>
        After each session most patients leave the department and return to lodging. A
        conventional course can still mean several weeks in India — that stay, not the
        five-minute beam-on time, is what you should plan around.
      </P>

      <H2 id="cost">External Beam Radiation Therapy cost</H2>
      <P>
        Cost varies enormously. A government centre, a mid-range private campus and a
        premium international-patient hospital may quote very different amounts for what
        looks like the same treatment.
      </P>
      <P>
        Major factors: cancer type and stage, treatment objective, number of fractions,
        3D-CRT versus IMRT/IGRT/VMAT, planning complexity, hospital, city, radiation
        oncologist, imaging, immobilisation, concurrent chemotherapy, and whether the
        patient is travelling.
      </P>
      <P>
        A 2026 Indian oncology source reports broad radiation-treatment ranges of roughly
        ₹1.2 lakh–₹4 lakh for many conventional and advanced courses, with more
        sophisticated techniques costing more. Medical-tourism sources put the wider
        Indian radiation-therapy market at approximately $1,000–$6,000+, depending on
        technique and hospital. Premium international-patient packages can be higher.
        Figures on this page are planning ranges, not quotes.
      </P>

      <H3>EBRT cost in India — major medical cities</H3>
      <P>
        Indicative full-course radiation/EBRT planning ranges in USD. GAF Healthcare currently
        lists named consultants in five of these cities.
      </P>
      <div className="mt-6 overflow-x-auto rounded-2xl border border-border">
        <table className="w-full min-w-[28rem] text-left text-sm">
          <thead className="bg-secondary/60 text-xs tracking-[0.16em] uppercase text-muted-foreground">
            <tr>
              <th className="px-4 py-3 font-medium">City</th>
              <th className="px-4 py-3 font-medium">Planning range (USD)</th>
              <th className="px-4 py-3 font-medium">On GAF Healthcare</th>
            </tr>
          </thead>
          <tbody>
            {indiaCityCosts.map((row) => (
              <tr key={row.city} className="border-t border-border bg-card">
                <td className="px-4 py-3 font-medium">{row.city}</td>
                <td className="px-4 py-3 text-muted-foreground">{row.range}</td>
                <td className="px-4 py-3">
                  {row.listed ? (
                    <span className="flex flex-wrap gap-3">
                      <Link
                        href={hospitalsPath({ destination: "India", city: row.city, procedure: EBRT_NAME })}
                        className="underline-offset-4 hover:underline"
                      >
                        Hospitals
                      </Link>
                      <Link
                        href={doctorsPath({ destination: "India", city: row.city, procedure: EBRT_NAME })}
                        className="underline-offset-4 hover:underline"
                      >
                        Doctors
                      </Link>
                    </span>
                  ) : (
                    <Link href="/consult" className="text-muted-foreground underline-offset-4 hover:underline">
                      Request a match
                    </Link>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <P>
        These figures should not be read as the price of every standard EBRT course.
        Advanced treatments such as{" "}
        <Link href={costPath("Intensity-Modulated Radiotherapy (IMRT)")}>IMRT</Link>,{" "}
        <Link href={costPath("Image-Guided Radiotherapy (IGRT)")}>IGRT</Link>, VMAT,{" "}
        <Link href={costPath("Stereotactic Body Radiotherapy (SBRT)")}>SBRT</Link> and
        stereotactic radiation can raise the price substantially.
      </P>

      <H3>EBRT cost in popular medical-tourism destinations</H3>
      <P>
        Indicative market figures, not standardised hospital tariffs. India is the
        destination GAF Healthcare currently staffs with named radiation oncologists.
      </P>
      <div className="mt-6 overflow-x-auto rounded-2xl border border-border">
        <table className="w-full min-w-[28rem] text-left text-sm">
          <thead className="bg-secondary/60 text-xs tracking-[0.16em] uppercase text-muted-foreground">
            <tr>
              <th className="px-4 py-3 font-medium">Destination</th>
              <th className="px-4 py-3 font-medium">Full-course range (USD)</th>
            </tr>
          </thead>
          <tbody>
            {destinationCosts.map((row) => (
              <tr key={row.place} className="border-t border-border bg-card">
                <td className="px-4 py-3 font-medium">
                  {row.place === "India" ? (
                    <Link href={ebrtHospitals} className="underline-offset-4 hover:underline">
                      {row.place}
                    </Link>
                  ) : (
                    row.place
                  )}
                </td>
                <td className="px-4 py-3 text-muted-foreground">{row.range}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <P>
        *Mexico figures vary depending on publicly funded versus private care. Singapore
        is difficult to compare because subsidised domestic bills and private
        international treatment sit on different schedules.
      </P>

      <H3>Why India is used for radiation treatment</H3>
      <P>
        Radiation-oncology infrastructure is concentrated in{" "}
        <Link href={hospitalsPath({ destination: "India", city: "Delhi NCR" })}>Delhi NCR</Link>,{" "}
        <Link href={hospitalsPath({ destination: "India", city: "Mumbai" })}>Mumbai</Link>,{" "}
        <Link href={hospitalsPath({ destination: "India", city: "Chennai" })}>Chennai</Link>,{" "}
        <Link href={hospitalsPath({ destination: "India", city: "Bengaluru" })}>Bengaluru</Link>{" "}
        and{" "}
        <Link href={hospitalsPath({ destination: "India", city: "Hyderabad" })}>Hyderabad</Link>
        . International patients may have access to modern linacs, IMRT, IGRT, VMAT,
        SBRT, SRS,{" "}
        <Link href={costPath("CyberKnife")}>CyberKnife</Link> at selected centres,{" "}
        <Link href={costPath("Proton Beam Therapy")}>proton therapy</Link> at selected
        centres (including{" "}
        <Link href="/hospitals/apollo-proton-cancer-centre">Apollo Proton Cancer Centre</Link>
        ), and{" "}
        <Link href={costPath("Brachytherapy")}>brachytherapy</Link>. Cost should not be
        the only factor: ask about the specific cancer, the named oncologist, technology,
        planning and QA, accreditation, imaging, international-desk support, and
        follow-up after you go home. See{" "}
        <Link href="/blogs/when-proton-is-worth-the-flight">when protons are worth the flight</Link>
        .
      </P>

      <H2 id="package">What is usually included in an EBRT package?</H2>
      <div className="mt-6 grid gap-6 sm:grid-cols-2">
        <div className="rounded-2xl border border-border bg-card p-6">
          <p className="text-xs tracking-[0.18em] uppercase text-gold">Usually included</p>
          <ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-muted-foreground">
            <li>Radiation oncologist consultation</li>
            <li>CT simulation</li>
            <li>Treatment planning</li>
            <li>Dosimetry</li>
            <li>Medical physics quality assurance</li>
            <li>Immobilisation device where required</li>
            <li>Radiation delivery</li>
            <li>On-treatment reviews</li>
            <li>Routine monitoring</li>
          </ul>
        </div>
        <div className="rounded-2xl border border-border bg-card p-6">
          <p className="text-xs tracking-[0.18em] uppercase text-gold">Often separate</p>
          <ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-muted-foreground">
            <li>PET-CT</li>
            <li>Diagnostic MRI</li>
            <li>Biopsy/pathology</li>
            <li>Blood tests</li>
            <li>Chemotherapy, immunotherapy, hormone therapy</li>
            <li>Hospital admission</li>
            <li>Treatment of complications</li>
            <li>Accommodation, flights, visa, local transport</li>
          </ul>
        </div>
      </div>
      <P>
        Ask for an itemized quotation rather than comparing only a headline price.{" "}
        <Link href={`/consult?treatment=external-beam-radiotherapy-ebrt`}>We will collect that quote</Link>{" "}
        against a named campus.
      </P>

      <H2 id="international">EBRT for international patients</H2>
      <P>Before travelling, send biopsy/pathology, previous treatment records, CT/MRI/PET, operative reports, prior radiation records if any, current medication list and recent bloods. The oncologist can then say whether the case is EBRT, IMRT, IGRT, SBRT/SRS, brachytherapy, or something else. For a 4–7 week course, lodging near the hospital matters because daily travel becomes difficult.</P>

      <H3>EBRT vs surgery and chemotherapy</H3>
      <P>
        EBRT and surgery are not always alternatives. Some cancers need surgery plus
        radiation; others radiation plus chemotherapy; selected cases radiation alone.
        EBRT is a local treatment. Chemotherapy is generally systemic. They may run
        together as concurrent chemoradiation.
      </P>

      <H2 id="recovery">How long it takes, and recovery</H2>
      <P>
        Beam-on time can be short. The journey is consultation, CT simulation, planning,
        quality assurance, daily fractions, then follow-up. A five-minute treatment can
        still require a five- or six-week schedule. Unlike surgery, there is usually no
        recovery bed after each fraction. Fatigue may increase as the course proceeds.
        After the last fraction the team schedules review of side effects, response,
        further treatment and surveillance imaging.
      </P>
      <P>
        Short-stay stereotactic courses are a different product — read{" "}
        <Link href="/blogs/srs-sbrt-and-a-short-stay">SRS and SBRT travel notes</Link>.
      </P>

      <H2 id="faq">Frequently asked questions</H2>
      <Accordion type="single" collapsible className="mt-6">
        {ebrtFaqs.map((item, i) => (
          <AccordionItem key={item.q} value={`faq-${i}`}>
            <AccordionTrigger className="text-base">{item.q}</AccordionTrigger>
            <AccordionContent className="text-muted-foreground">{item.a}</AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>

      <H2 id="takeaway">Final takeaway</H2>
      <P>
        External Beam Radiation Therapy is not one treatment. It includes conventional
        radiation and techniques such as IMRT, IGRT, VMAT, SRS and SBRT. The right
        technique depends on the cancer, stage, location, intent and organs that must be
        spared.
      </P>
      <P>
        For international patients, India can combine experienced radiation oncologists,
        advanced technology and comparatively competitive costs. The useful question is
        not only which country is cheapest. It is which centre can provide the
        appropriate technique, an experienced team, safe planning, and a transparent
        total cost for this cancer. An individualized review and an itemized hospital
        quotation beat a generic online price.
      </P>
      <P>
        Cost figures here are indicative planning ranges, not guaranteed quotations. The
        final price should be confirmed after the radiation oncologist reviews the
        diagnosis, scans, treatment intent and required number of fractions.
      </P>
    </article>
  );
}
