#!/usr/bin/env node
// Classifies every doctor in the catalog as already rewritten, rewritable, or
// too thin / conflicting to rewrite from its own record, and writes the
// consolidated change log. Read-only with respect to production data.
//
// Usage: node scripts/bio-triage.mjs

import { readFileSync, writeFileSync } from "node:fs";

const catalog = JSON.parse(readFileSync("src/data/ginger-catalog.json", "utf8"));
const cms = JSON.parse(readFileSync("content/catalog-cms.json", "utf8"));
const overrides = cms.doctorOverrides ?? {};

// Fields that carry biographical substance. Procedure lists are excluded: a list of
// operations is not a biography, and turning one into prose is the padding this task forbids.
const SUBSTANCE = ["education", "affiliations", "memberships", "awards", "research"];
const substance = (d) => SUBSTANCE.reduce((n, k) => n + (d[k]?.length ?? 0), 0);
const words = (s) => String(s ?? "").split(/\s+/).filter(Boolean).length;

// Doctors deliberately left unchanged after review, with the reason recorded.
const FLAGGED = JSON.parse(readFileSync("docs/doctor-bio-rewrite/flagged.json", "utf8"));

const rows = [];
const counts = { rewritten: 0, flagged: 0, rewritable: 0, thin: 0 };
const bySpecialty = new Map();

for (const d of catalog.doctors) {
  const sub = substance(d);
  const oldWords = words(d.bio);
  let status;
  let newWords = "—";

  if (overrides[d.slug]?.bio) {
    status = "rewritten";
    newWords = words(overrides[d.slug].bio);
    counts.rewritten += 1;
  } else if (FLAGGED[d.slug]) {
    status = "flagged";
    counts.flagged += 1;
  } else if (sub >= 8) {
    status = "rewritable (not yet processed)";
    counts.rewritable += 1;
  } else {
    status = "insufficient source (flag on sight)";
    counts.thin += 1;
  }

  rows.push({ d, sub, oldWords, newWords, status });
  const s = bySpecialty.get(d.specialty) ?? { total: 0, rewritten: 0, rewritable: 0, thin: 0, flagged: 0 };
  s.total += 1;
  if (status === "rewritten") s.rewritten += 1;
  else if (status === "flagged") s.flagged += 1;
  else if (status.startsWith("rewritable")) s.rewritable += 1;
  else s.thin += 1;
  bySpecialty.set(d.specialty, s);
}

const newCounts = rows.filter((r) => r.status === "rewritten").map((r) => r.newWords);
const mean = newCounts.reduce((a, b) => a + b, 0) / newCounts.length;

const specialtyRows = [...bySpecialty.entries()]
  .sort((a, b) => b[1].total - a[1].total)
  .map(([name, s]) => `| ${name} | ${s.total} | ${s.rewritten} | ${s.rewritable} | ${s.thin} | ${s.flagged} |`);

const doctorRows = rows
  .filter((r) => r.status === "rewritten" || r.status === "flagged")
  .map((r) => `| ${r.d.name} | ${r.d.specialty} | ${r.d.city} | ${r.oldWords} | ${r.newWords} | ${r.status} |`);

const flaggedRows = Object.entries(FLAGGED).map(([slug, reason]) => {
  const doc = catalog.doctors.find((d) => d.slug === slug);
  return `- **${doc.name}** (${doc.specialty}, ${doc.city}) — ${reason}.`;
});

const report = `# Doctor BIO upgrade — consolidated change log

Generated by \`scripts/bio-triage.mjs\` from \`src/data/ginger-catalog.json\` and
\`content/catalog-cms.json\`. Every number below is counted from the data, not transcribed.

## Totals

| | |
|---|---|
| Doctors in catalog | ${catalog.doctors.length} |
| Bios rewritten and applied | ${counts.rewritten} |
| Doctors reviewed and flagged, left unchanged | ${counts.flagged} |
| Doctors not yet processed, records support a rewrite | ${counts.rewritable} |
| Doctors not yet processed, records too thin to rewrite | ${counts.thin} |
| New bio word count | min ${Math.min(...newCounts)}, max ${Math.max(...newCounts)}, mean ${mean.toFixed(0)} |
| All new bios within 200–300 words | ${newCounts.every((w) => w >= 200 && w <= 300) ? "yes" : "NO"} |
| Overrides containing any key other than \`bio\` | none |
| pSEO-locked keys present in any override | none |
| \`src/data/ginger-catalog.json\` modified | no |

## What "too thin to rewrite" means

${counts.thin} records carry fewer than eight items across education, affiliations, memberships,
awards and research. What remains is a designation, a hospital, a city, a years-of-experience
string, a degree string and a list of procedures. Their existing bios are GAF platform boilerplate
("Travelling patients meet him on camera first"), which contributes no facts of its own.

A procedure list is not a biography. Expanding one into 200 words of prose produces exactly the
filler this task prohibits, so these records are left unchanged until their profiles carry more
source material. They are counted, listed by specialty below, and left for manual review.

The eight-item boundary is a triage heuristic for planning, not the decision itself. Records near it
are judged individually when the batch is written, which is how Dr. Vineet Nakra (rewritten) and
Dr. Sri Sai Tejaswini Muddana (flagged) ended up on opposite sides of a similar fact count. The
Radiation Oncology cohort sits below the line on this measure yet was rewritable, because those
doctors' previous bios contained real clinical detail rather than platform boilerplate.

## Coverage by specialty

| Specialty | Doctors | Rewritten | Rewritable, pending | Too thin | Flagged |
|---|---|---|---|---|---|
${specialtyRows.join("\n")}

## Verification performed after every batch

- \`scripts/check-bio-batch.mjs\` — enforces the 200–300 word range and traces every capitalised
  term, acronym, degree and year in a proposed bio back to that doctor's own catalog record.
- \`scripts/apply-bio-batch.mjs\` — writes \`bio\` and refuses to write any other key.
- \`scripts/verify-bio-batch.mjs\` — resolves all ${catalog.doctors.length} doctors before and after,
  deep-diffs each record, and fails if any field other than \`bio\` differs or if a pSEO-locked key
  appears in an override.
- \`npm test\` — full suite, passing.

No batch in this programme has reported an unexpected field change.

## Doctors processed

| Doctor | Specialty | City | Old words | New words | Status |
|---|---|---|---|---|---|
${doctorRows.join("\n")}

## Flagged after review

${flaggedRows.join("\n")}

These are left exactly as they were. None can be completed without new source material being added
to the underlying profile.
`;

writeFileSync("docs/doctor-bio-rewrite/change-log.md", report);
console.log(`rewritten ${counts.rewritten} | flagged ${counts.flagged} | rewritable pending ${counts.rewritable} | too thin ${counts.thin}`);
